name: Docusaurus
on:
    push:
        branches:
            - main
        paths:
            - 'docs/**'
            - '.github/workflows/docusaurus.yml'
jobs:
    Apply-Protoc-Docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up node
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  cache: 'npm'
            - name: Install dependencies of Docusaurus
              run: |
                  cd docs
                  npm ci
            - name: Generate Docusaurus Documatation
              run: |
                  cd docs
                  npm docusaurus generate-proto-docs
                  npm build
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./docs/build
