name: Protocol Buffers Generate And Push Back
on:
    push:
        branches:
        - main
        paths:
        - 'proto/**/**.proto'
        - '.github/workflows/protoc-pushback.yml'

jobs:
    generate:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Generate
              run: |
                ./scripts/protoc-generate.sh
            - name: Commit And Push
              uses: stefanzweifel/git-auto-commit-action@v4.2.0
              with:
                commit_message: "gen: generate proto"
